name: "Build and Release"

on:
  pull_request:
  push:
    tags:
      - "v*.*.*"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix build --experimental-features 'nix-command flakes' --no-link .#defaultPackage.x86_64-linux
      - name: Zip the result folder
        run: |
          mkdir -p output
          cp -r result/* output/
          zip -r release.zip output
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
